site_name: Software + ML
site_url: https://softwareplus.ml
repo_url: https://github.com/baluyotraf/softwareplusml
repo_name: baluyotraf/softwareplusml
edit_uri: ""

nav:
  - Home: index.md
  - Blogs:
      - Sample Blog: blogs/sample.md
  - Projects: projects.md
  - About: about.md

theme:
  name: material
  language: en
  palette: 
    primary: blue grey
    accent: light blue
  icon:
    logo: fontawesome/solid/robot
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top

extra_css:
  - stylesheets/extra.css
  
extra:
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/baluyotraf/
      name: baluyotraf

copyright: Copyright &copy; 2022 Raffaello Baluyot